[project]
name = "perexchange-monorepo"
version = "1.0.0"
description = "Monorepo for perexchange project"
requires-python = ">=3.9"

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.ruff]
line-length = 100
